version: '0.1.1'

networks:
  app-network-public:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
  sqldata:
  sqllog:
  sqlbackup:

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: db-sqlserver
    networks:
      - app-network-public
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password12345'
      MSSQL_DATA_DIR: '/var/opt/sqlserver/data'
      MSSQL_LOG_DIR: '/var/opt/sqlserver/log'
      MSSQL_BACKUP_DIR: '/var/opt/sqlserver/backup'
    ports:
      - '1433:1433'
    volumes:
      - sql-server-data:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
      - c:/src/docker/shared:/usr/shared
